from dotenv import load_dotenv
from graph import run_stratumai
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.units import mm
from io import BytesIO
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import time
import re
import os

load_dotenv(override=True)


# ─────────────────────────────────────────
# PDF GENERATOR
# ─────────────────────────────────────────
def generate_pdf(company_name: str, report: str) -> bytes:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=20*mm,   bottomMargin=20*mm
    )

    style_title   = ParagraphStyle("title",   fontSize=20, fontName="Helvetica-Bold",    textColor=HexColor("#0A0A0F"), spaceAfter=14,  alignment=1)
    style_company = ParagraphStyle("company", fontSize=15, fontName="Helvetica-Bold",    textColor=HexColor("#4FACFE"), spaceAfter=6, spaceBefore=6,  alignment=1)
    style_date    = ParagraphStyle("date",    fontSize=9,  fontName="Helvetica",         textColor=HexColor("#888888"), spaceAfter=10, alignment=1)
    style_h1      = ParagraphStyle("h1",      fontSize=15, fontName="Helvetica-Bold",    textColor=HexColor("#0A0A0F"), spaceBefore=5, spaceAfter=4)
    style_h2      = ParagraphStyle("h2",      fontSize=12, fontName="Helvetica-Bold",    textColor=HexColor("#1a1a2e"), spaceBefore=4,  spaceAfter=3)
    style_bullet  = ParagraphStyle("bullet",  fontSize=10, fontName="Helvetica",         textColor=HexColor("#333333"), leftIndent=12, spaceBefore=2, spaceAfter=2, bulletText="•")
    style_body    = ParagraphStyle("body",    fontSize=10, fontName="Helvetica",         textColor=HexColor("#333333"), spaceBefore=2, spaceAfter=2, leading=14)
    style_footer  = ParagraphStyle("footer",  fontSize=8,  fontName="Helvetica-Oblique", textColor=HexColor("#aaaaaa"), alignment=1)

    story = []
    story.append(Paragraph("StratumAI Intelligence Brief", style_title))
    story.append(Paragraph(company_name.upper(), style_company))
    story.append(Paragraph(f"Generated on {time.strftime('%B %d, %Y')}", style_date))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#4FACFE")))
    story.append(Spacer(1, 2*mm))

    for line in report.split("\n"):
        clean = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
        clean = re.sub(r"\*(.+?)\*",     r"\1", clean)
        clean = re.sub(r"`(.+?)`",        r"\1", clean)
        clean = clean.replace("\u2014", "-").replace("\u2013", "-")
        clean = clean.replace("\u201c", '"').replace("\u201d", '"')
        clean = clean.replace("\u2018", "'").replace("\u2019", "'")
        clean = clean.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        if clean.startswith("# "):
            story.append(Spacer(1, 4*mm))
            story.append(Paragraph(clean[2:], style_h1))
            story.append(Spacer(1, 2*mm))
            story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#cccccc")))
            story.append(Spacer(1, 3*mm))
        elif clean.startswith("## "):
            story.append(Spacer(1, 3*mm))
            story.append(Paragraph(clean[3:], style_h2))
            story.append(Spacer(1, 1*mm))
            story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#eeeeee")))
            story.append(Spacer(1, 2*mm))
        elif clean.startswith("- ") or clean.startswith("* "):
            story.append(Paragraph(clean[2:], style_bullet))
        elif clean.strip() == "":
            story.append(Spacer(1, 3*mm))
        else:
            story.append(Paragraph(clean, style_body))

    story.append(Spacer(1, 5*mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#cccccc")))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph("Generated by StratumAI - Multi-Agent Competitive Intelligence System", style_footer))

    doc.build(story)
    return buffer.getvalue()


# ─────────────────────────────────────────
# HTML EMAIL BODY
# ─────────────────────────────────────────
def build_html_email(company_name: str, report: str) -> str:
    html_lines = []
    for line in report.split("\n"):
        line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)

        if line.startswith("# "):
            html_lines.append(f"<h1 style='color:#0A0A0F;border-bottom:2px solid #4FACFE;padding-bottom:3px'>{line[2:]}</h1>")
        elif line.startswith("## "):
            html_lines.append(f"<h2 style='color:#1a1a2e;margin-top:24px'>{line[3:]}</h2>")
        elif line.startswith("- ") or line.startswith("* "):
            html_lines.append(f"<li style='margin:2px 0;color:#333'>{line[2:]}</li>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            html_lines.append(f"<p style='color:#333;line-height:1.6'>{line}</p>")

    body_html = "\n".join(html_lines)

    return f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="UTF-8"></head>
    <body style="margin:0;padding:0;background:#f4f4f4;font-family:'Helvetica Neue',sans-serif;">

      <div style="background:linear-gradient(135deg,#0A0A0F,#1a1a3e);padding:40px 20px;text-align:center;">
        <h1 style="color:white;font-size:2rem;margin:0;">🧠 StratumAI</h1>
        <p style="color:#94A3B8;margin:8px 0 0;">Multi-Agent Competitive Intelligence System</p>
      </div>

      <div style="background:#4FACFE;padding:16px;text-align:center;">
        <h2 style="color:white;margin:0;font-size:1.4rem;">Intelligence Brief: {company_name.upper()}</h2>
        <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:0.9rem;">{time.strftime('%B %d, %Y')}</p>
      </div>

      <div style="max-width:700px;margin:0 auto;background:white;padding:40px;border-radius:0 0 12px 12px;">
        {body_html}
        <div style="margin-top:40px;padding-top:20px;border-top:1px solid #eee;text-align:center;">
          <p style="color:#aaa;font-size:0.8rem;">
            Generated by StratumAI &mdash; Multi-Agent Competitive Intelligence System<br>
            PDF report attached to this email.
          </p>
        </div>
      </div>

    </body>
    </html>
    """


# ─────────────────────────────────────────
# SEND EMAIL VIA GMAIL SMTP
# ─────────────────────────────────────────
def send_report_email(company_name: str, report: str, recipient_email: str):
    gmail_address  = os.getenv("GMAIL_ADDRESS")
    gmail_password = os.getenv("GMAIL_APP_PASSWORD")

    print(f"  Generating PDF for {company_name}...")
    pdf_bytes = generate_pdf(company_name, report)

    print(f"  Building email...")
    html_body = build_html_email(company_name, report)

    # Build email
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"🧠 StratumAI Brief: {company_name} — {time.strftime('%B %d, %Y')}"
    msg["From"]    = gmail_address
    msg["To"]      = recipient_email

    # HTML body
    msg.attach(MIMEText(html_body, "html"))

    # PDF attachment
    pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
    pdf_attachment.add_header(
        "Content-Disposition",
        "attachment",
        filename=f"{company_name.lower()}_intel.pdf"
    )
    msg.attach(pdf_attachment)
    print(f"  ✅ PDF attached {recipient_email}!")
    # Send via Gmail SMTP
    context = ssl.create_default_context()
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls(context=context)
        server.login(gmail_address, gmail_password)
        server.sendmail(gmail_address, recipient_email, msg.as_string())

    print(f"  ✅ Email sent successfully to {recipient_email}!")


# ─────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────
def send_intelligence_report(company_name: str, recipient_email: str):
    print(f"\n🚀 Generating report for: {company_name}")
    report = run_stratumai(company_name)

    print(f"\n📧 Sending email to: {recipient_email}")
    send_report_email(company_name, report, recipient_email)
    return report


if __name__ == "__main__":
    company   = input("Company to analyze: ")
    recipient = input("Send report to (email): ")
    send_intelligence_report(company, recipient)